/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgendamentoConfirmationDialog: typeof import('./components/agendamento/AgendamentoConfirmationDialog.vue')['default']
    AgendamentoFilters: typeof import('./components/agendamento/AgendamentoFilters.vue')['default']
    AgendamentoMentoriaDetails: typeof import('./components/agendamento/AgendamentoMentoriaDetails.vue')['default']
    AgendamentoMentoriasList: typeof import('./components/agendamento/AgendamentoMentoriasList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppSnackbar: typeof import('./components/AppSnackbar.vue')['default']
    CancelTutoringDialog: typeof import('./components/profile/CancelTutoringDialog.vue')['default']
    EditMentoringSessionDialog: typeof import('./components/profile/EditMentoringSessionDialog.vue')['default']
    MentoriaCard: typeof import('./components/MentoriaCard.vue')['default']
    MentoriaConfirmationDialog: typeof import('./components/profile/MentoriaConfirmationDialog.vue')['default']
    MentoringDetailsDialog: typeof import('./components/profile/MentoringDetailsDialog.vue')['default']
    ProfileSectionConta: typeof import('./components/profile/ProfileSectionConta.vue')['default']
    ProfileSectionDisponibilidades: typeof import('./components/profile/ProfileSectionDisponibilidades.vue')['default']
    ProfileSectionInicio: typeof import('./components/profile/ProfileSectionInicio.vue')['default']
    ProfileSectionMentoriasMentor: typeof import('./components/profile/ProfileSectionMentoriasMentor.vue')['default']
    ProfileSectionMentoriasMentorado: typeof import('./components/profile/ProfileSectionMentoriasMentorado.vue')['default']
    ProfileSectionPerfil: typeof import('./components/profile/ProfileSectionPerfil.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserProfileSidebar: typeof import('./components/profile/UserProfileSidebar.vue')['default']
  }
}
