/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/aboutUs': RouteRecordInfo<'/aboutUs', '/aboutUs', Record<never, never>, Record<never, never>>,
    '/agendamento': RouteRecordInfo<'/agendamento', '/agendamento', Record<never, never>, Record<never, never>>,
    '/cadastre': RouteRecordInfo<'/cadastre', '/cadastre', Record<never, never>, Record<never, never>>,
    '/chatMentor': RouteRecordInfo<'/chatMentor', '/chatMentor', Record<never, never>, Record<never, never>>,
    '/discipline': RouteRecordInfo<'/discipline', '/discipline', Record<never, never>, Record<never, never>>,
    '/faq': RouteRecordInfo<'/faq', '/faq', Record<never, never>, Record<never, never>>,
    '/forgotPassword': RouteRecordInfo<'/forgotPassword', '/forgotPassword', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mindMap': RouteRecordInfo<'/mindMap', '/mindMap', Record<never, never>, Record<never, never>>,
    '/perfil': RouteRecordInfo<'/perfil', '/perfil', Record<never, never>, Record<never, never>>,
    '/resetPasswordForm': RouteRecordInfo<'/resetPasswordForm', '/resetPasswordForm', Record<never, never>, Record<never, never>>,
  }
}
